apiVersion: v1
kind: Secret
metadata:
  name: system-service-secret
  labels:
    app: system-service
type: Opaque
stringData:
  # 数据库敏感信息
  DB_PASSWORD: "123456"
  
  # 认证密钥
  ACCESS_SECRET: "35a920489e4da3a6faeca6d368d0ab827fc98313443baf2afcd117d8bae3bdc4"
  
  # Redis 密码 (如果使用)
  REDIS_PASSWORD: ""
